### ISSUE TITLE
Pull Request Club

### ISSUE THREAD

**Issue by yewtc** [book/Config-INI-Reader-Multiline#1]
Hi, I've been allocated this module as part of the pull request club. I can't see any obvious changes to make and there are no outstanding  issues. In fact it seems to me that it makes sense to have a pull request on Config::INI to have multi-line as an option. Having said that - is ignoring trailing white-space ok?

**Comment by book** [comment]
Looking at this code again, and taking your comment into account, I wonder about one thing: how should whitespace be handled.

I think we need more test data, with edge cases like:
```
# no space at the end of the line or the beginning of the continuation line
foo = bar\
baz
```
Should this give the value `bar baz` or `barbaz`?

It's probably worth looking at how `Config::INI::Reader` itself handles whitespace, and follow its example.

**Comment by yewtc** [comment]
I found - and fixed a 'real' issue, so Ill close this one.

**Comment by yewtc** [comment]
I found - and fixed a 'real' issue, so Ill close this one.
